import type {
  AvailabilityStatus,
  Candidate,
  CandidateApi,
  CandidateDetail,
} from '../types/candidate';

const AVATAR_BASE = 'https://ui-avatars.com/api/?background=0D8ABC&color=fff&name=';

const normalizeAvailability = (
  availability: CandidateApi['availability'],
): AvailabilityStatus => {
  if (typeof availability === 'string') {
    const value = availability.toLowerCase();
    if (value.includes('immediate')) return 'immediate';
    if (value.includes('2')) return '2 weeks';
    if (value.includes('week')) return '2 weeks';
    if (value.includes('month')) return '1 month';
    if (value.includes('notice')) return 'notice';
    if (value.includes('available')) return 'available';
    if (value.includes('unavailable')) return 'unavailable';
  }

  if (availability === true) return 'available';
  if (availability === false) return 'unavailable';

  return 'unknown';
};

const normalizeSkills = (skills?: string[] | null) => {
  if (!skills || !Array.isArray(skills)) return [];
  return skills.filter(Boolean);
};

const buildCareerTimeline = (candidate: Candidate): CandidateDetail['careerTimeline'] => {
  if (!candidate.createdAt && !candidate.currentCompany) return undefined;
  return [
    {
      year: candidate.createdAt
        ? new Date(candidate.createdAt).getFullYear().toString()
        : 'Present',
      role: candidate.jobTitle,
      company: candidate.currentCompany,
    },
  ];
};

const buildWorkExperience = (candidate: Candidate): CandidateDetail['workExperience'] => {
  if (!candidate.currentCompany) return undefined;
  return [
    {
      company: candidate.currentCompany,
      role: candidate.jobTitle,
      duration: `${candidate.experience} yrs`,
      description: candidate.about || 'Experience details not provided by the AI service.',
    },
  ];
};

export const mapCandidateFromApi = (candidate: CandidateApi): Candidate => {
  const match =
    candidate.match_percentage ??
    candidate.match_percent ??
    candidate.matchPercentage ??
    0;

  const mapped: Candidate = {
    id: String(candidate.id),
    name: candidate.name || 'Unnamed Candidate',
    jobTitle: candidate.title || candidate.jobTitle || 'Unknown Role',
    currentCompany: candidate.company || candidate.currentCompany || 'Not specified',
    experience: candidate.experience_years ?? candidate.experience ?? 0,
    location: candidate.location || 'Not specified',
    skills: normalizeSkills(candidate.skills),
    photoUrl:
      candidate.photo_url ||
      candidate.photoUrl ||
      candidate.image_url ||
      `${AVATAR_BASE}${encodeURIComponent(candidate.name || 'Candidate')}`,
    availability: normalizeAvailability(candidate.availability),
    matchPercentage: Math.min(100, Math.max(0, Math.round(match))),
    matchColor: candidate.match_color,
    email: candidate.email,
    phone: candidate.phone,
    strengths: candidate.strengths,
    areasToProbe: candidate.areas_to_probe || candidate.areasToProbe,
    aiVerdict: candidate.ai_verdict || candidate.aiVerdict,
    about: candidate.about,
    education: candidate.education,
    createdAt: candidate.created_at,
    isContactUnlocked: false,
  };

  return mapped;
};

export const mapCandidatesFromApi = (candidates: CandidateApi[] = []): Candidate[] =>
  candidates.map(mapCandidateFromApi);

export const mapCandidateDetailFromApi = (candidate: CandidateApi): CandidateDetail => {
  const baseCandidate = mapCandidateFromApi(candidate);
  return {
    ...baseCandidate,
    strengths: baseCandidate.strengths || [],
    areasToProbe: baseCandidate.areasToProbe || [],
    aiVerdict:
      baseCandidate.aiVerdict ||
      `AI matched ${baseCandidate.name} as ${baseCandidate.jobTitle}.`,
    about:
      baseCandidate.about ||
      'This candidate summary is generated by the AI search service.',
    careerTimeline: buildCareerTimeline(baseCandidate),
    workExperience: buildWorkExperience(baseCandidate),
  };
};

export const candidateToDetail = (candidate: Candidate): CandidateDetail => ({
  ...candidate,
  strengths: candidate.strengths && candidate.strengths.length > 0 ? candidate.strengths : [],
  areasToProbe:
    candidate.areasToProbe && candidate.areasToProbe.length > 0 ? candidate.areasToProbe : [],
  aiVerdict:
    candidate.aiVerdict ||
    `AI matched ${candidate.name} as ${candidate.jobTitle}.`,
  about:
    candidate.about ||
    'This candidate summary is generated by the AI search service.',
  careerTimeline:
    (candidate as CandidateDetail).careerTimeline &&
    (candidate as CandidateDetail).careerTimeline!.length > 0
      ? (candidate as CandidateDetail).careerTimeline
      : buildCareerTimeline(candidate),
  workExperience:
    (candidate as CandidateDetail).workExperience &&
    (candidate as CandidateDetail).workExperience!.length > 0
      ? (candidate as CandidateDetail).workExperience
      : buildWorkExperience(candidate),
});

